#!/usr/bin/env python3
"""S3b.1 overlay — target-under-thin vs Fournier 2000 Fig 6A Déa observations.

Plan: PLAN_FULL_B35_PER_PHYTOMER_BOOKKEEPING_2026-04-23.md §Pre-work (S3b.1).

Produces:
  * s3b1_overlay_fournier_dea.png — 7 panels (ranks 9-15), target vs observed
  * console summary of per-rank RMSE and axis offsets

The findings note `s3b1_systematic_residual.md` is hand-authored (not
regenerated by this script) so that the plastochron-drift interpretation and
S3b.5 tolerance recommendation stay stable across reruns.

Axis alignment: sim counts TT on Andrieu axis (Tb=9.8) from SOWING; Fournier 2000
counts TT since plant EMERGENCE. Per-rank we fit an offset delta_n such that
sim_IL_n(TT_A - delta_n) matches observed_IL_n(TT). The mean of delta_n across
ranks estimates sim-to-Fournier axis offset; per-rank deviation from the mean
is part of the systematic residual.

Run:
    cpbenv/bin/python3 dart/coupling/tests/baselines/s3b1_overlay_fournier_dea.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np

BASELINE_DIR = Path(__file__).resolve().parent
SIM_JSON = BASELINE_DIR / "s3b1_thin_target_per_rank.json"
OBS_JSON = BASELINE_DIR / "fournier2000_dea_fig6a_per_rank.json"
OUT_PNG = BASELINE_DIR / "s3b1_overlay_fournier_dea.png"


def load_sim():
    d = json.loads(SIM_JSON.read_text())
    tt_a = np.array([x["tt_andrieu"] for x in d["trajectory"]], dtype=float)
    per_rank = {}
    n_ranks = d["n_ranks"]
    for n in range(1, n_ranks + 1):
        per_rank[n] = np.array([x["target_per_rank_cm"][n - 1] for x in d["trajectory"]], dtype=float)
    return tt_a, per_rank


def load_obs():
    d = json.loads(OBS_JSON.read_text())
    tt = np.array(d["tt_deg_cd"], dtype=float)
    per_rank = {int(k): np.array(v, dtype=float) for k, v in d["per_rank_il_cm"].items()}
    return tt, per_rank, d


def best_offset(sim_tt, sim_il, obs_tt, obs_il, search_range=(-100.0, 500.0), step=1.0):
    """Find delta minimizing RMSE of sim_il(obs_tt + delta) vs obs_il.

    Returns (delta, rmse_at_delta, rmse_at_zero_offset).
    """
    # Only consider observation points where obs_il > 0.5 cm — below that, both
    # curves are near zero and the fit has no leverage.
    active = obs_il > 0.5
    if active.sum() < 3:
        return np.nan, np.nan, np.nan
    best_delta = 0.0
    best_rmse = np.inf
    deltas = np.arange(search_range[0], search_range[1] + step, step)
    for delta in deltas:
        interp_sim = np.interp(obs_tt[active] + delta, sim_tt, sim_il, left=0.0, right=np.nan)
        if np.any(np.isnan(interp_sim)):
            continue
        rmse = float(np.sqrt(np.mean((interp_sim - obs_il[active]) ** 2)))
        if rmse < best_rmse:
            best_rmse = rmse
            best_delta = delta
    rmse_zero = float(np.sqrt(np.mean(
        (np.interp(obs_tt[active], sim_tt, sim_il, left=0.0, right=np.nan) - obs_il[active]) ** 2
    )))
    return best_delta, best_rmse, rmse_zero


def main():
    sim_tt, sim_per_rank = load_sim()
    obs_tt, obs_per_rank, _ = load_obs()

    ranks = sorted(obs_per_rank.keys())
    print(f"S3b.1 overlay: target-under-thin  vs  Fournier 2000 Fig 6A Déa ({len(ranks)} ranks)")

    results = {}
    for n in ranks:
        sim_il = sim_per_rank[n]
        obs_il = obs_per_rank[n]
        delta, rmse_at_delta, rmse_at_zero = best_offset(sim_tt, sim_il, obs_tt, obs_il)
        results[n] = {
            "delta_tt_cd": delta,
            "rmse_at_delta_cm": rmse_at_delta,
            "rmse_at_zero_offset_cm": rmse_at_zero,
            "obs_peak_cm": float(obs_il.max()),
            "sim_peak_cm": float(sim_il.max()),
        }
        print(f"  rank {n:2d}: obs peak {obs_il.max():5.1f} cm  sim peak {sim_il.max():5.1f} cm  "
              f"best Δ={delta:+6.1f} °Cd  RMSE(Δ)={rmse_at_delta:4.2f} cm  "
              f"RMSE(0)={rmse_at_zero:5.2f} cm")

    deltas = np.array([r["delta_tt_cd"] for r in results.values() if not np.isnan(r["delta_tt_cd"])])
    mean_delta = float(deltas.mean()) if deltas.size else 0.0
    std_delta = float(deltas.std()) if deltas.size else 0.0
    print(f"\nMean per-rank offset: Δ = {mean_delta:+6.1f} ± {std_delta:4.1f} °Cd")
    print("Interpretation: sim TT_A (since sowing) ≈ Fournier TT (since emergence) + Δ,")
    print(f"                i.e. sim records ~{mean_delta:.0f} °Cd of pre-emergence thermal time.")

    # --------- PNG render ---------
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ImportError:
        print("matplotlib unavailable — skipping PNG render")
        return 0

    ncols = 4
    nrows = (len(ranks) + ncols - 1) // ncols
    fig, axes = plt.subplots(nrows, ncols, figsize=(4 * ncols, 3 * nrows), sharey=True)
    axes_list = list(np.array(axes).flatten())

    for idx, n in enumerate(ranks):
        ax = axes_list[idx]
        r = results[n]
        delta = r["delta_tt_cd"]
        # Plot sim curve, shifted LEFT by delta so it lands on Fournier's native axis.
        ax.plot(sim_tt - delta, sim_per_rank[n], "b-", lw=1.4, label=f"sim target (shifted Δ={delta:+.0f})")
        ax.plot(obs_tt, obs_per_rank[n], "k^", ms=5, label="Fournier 2000 obs")
        ax.fill_between(obs_tt, obs_per_rank[n] - 1.0, obs_per_rank[n] + 1.0, color="gray", alpha=0.2, label="±1 cm digitization band")
        ax.set_title(f"rank {n}  RMSE={r['rmse_at_delta_cm']:.2f} cm", fontsize=10)
        ax.set_xlim(400, 800)
        ax.set_ylim(-1, 28)
        ax.grid(alpha=0.3)
        if idx == 0:
            ax.legend(fontsize=7, loc="upper left")
        if idx % ncols == 0:
            ax.set_ylabel("IL_n (cm)")
        if idx >= len(ranks) - ncols:
            ax.set_xlabel("TT since emergence (°Cd, Tb=9.8/10)")

    for idx in range(len(ranks), nrows * ncols):
        axes_list[idx].axis("off")

    fig.suptitle(
        f"S3b.1: target-under-thin vs Fournier 2000 Déa Fig 6A\n"
        f"per-rank axis offset Δ = {mean_delta:+.0f} ± {std_delta:.0f} °Cd (sim TT_A since sowing − Fournier TT since emergence)",
        fontsize=11)
    plt.tight_layout()
    plt.savefig(OUT_PNG, dpi=130)
    print(f"\nSaved overlay to {OUT_PNG}")
    print("Findings note is hand-authored at s3b1_systematic_residual.md — not regenerated here.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
