"""pm_notebook_loop.py — mirror the FSPM 2023 notebook loop pattern
(useCWGr=True, plant.simulate(dt) between PM substeps) and check
whether the entire 'PiafMunch broken on mature plants' diagnostic
arc collapses to a useCWGr=False harness artifact.

The notebook (`tutorial/jupyter/fspm_2023/3_sucrose_flux.ipynb`) loops:

    while sim < simMax:
        weather  = weather(sim)
        r.solve_photosynthesis(...)
        r.startPM(sim, sim+dt, 1, TairK, True, filename)
        # ... inspect Q_out ...
        r.plant.simulate(dt, verbose)         # <-- consumes CW_Gr
        sim += dt

Three targets selectable by --case:

  wheat_tutorial : Reproduce the published Lacointe-Giraud day-7.3
                   regime (BINARY CHECK -- if our PM run matches the
                   notebook reference numbers, the entire
                   useCWGr=False diagnostic chain was a harness bug).

  v3_maize       : V3 (21d) maize under Babst chamber-proxy met,
                   useCWGr=True. Looking for Rg > 0, load_eff > 30%,
                   C_ST_mean > CSTimin (i.e., gate doesn't pin).

  day55_maize    : Day-55 mature maize at saturating PAR. Looking for
                   physical Rg/Rm/Exud at the production scale.

Notebook reference (extracted from notebook output at day 7 0h, dt=0.083d):
  C_ST_mean  : 1.78 mmol/cm^3  (range 1.64 - 1.87)
  Rm         : 0.0104 mmol Suc cumulative over dt
  Gr         : 0.00725 mmol Suc
  Exud       : 0.0379 mmol Suc
  Sink split : Rm 18.8% / Gr 13.0% / Exud 68.2%
  AnSum      : 0.102 mmol Suc

PiafMunch follow-up #4 disposition (2026-05-08):
  The 10× cum_Q_Gr gap (model 7.56e-4 vs notebook 7.25e-3) is *engine*
  divergence, not parameter divergence. Upstream CPlantBox removed the
  legacy XylemFlux engine on 2025-12-19 (commits cdfe4dc6, da87db9c by
  Daniel Leitner). Hydraulic uptake is now solved by HydraulicModel_Meunier
  via PlantHydraulicParameters; the notebook reference was generated by
  the pre-removal XylemFlux engine. Under identical inputs (same plant,
  soil, kr/kx, RH/Tair) the new engine produces psiXyl 6−10× more
  negative, driving Fpsi → 0 on every node. Per-step refresh of kr/kx +
  psi_air via the new API (--legacy-perstep / --legacy-perstep-no-krlen)
  does NOT close the gap (verified 2026-05-08 with audit-psixyl). Either
  recalibrate the notebook reference against the new engine (full
  re-run + result diff against pre-2025-12-19 build), or treat 7.56e-4
  as the current-engine wheat-tutorial baseline (recommended).

NO useCWGr=False line in this script.  NO solver-side workarounds.
"""

import argparse
import os
import sys
import json
import time as _time
from pathlib import Path

import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(REPO_ROOT))
sys.path.insert(0, str(REPO_ROOT / "modelparameter" / "functional"))

from dart.coupling.config import (  # noqa: E402
    DEFAULT_XML, get_hydraulics_json, get_photosynthesis_json, get_phloem_json,
)
from dart.coupling.growth import grow_plant  # noqa: E402

WHEAT_XML = REPO_ROOT / "modelparameter/structural/plant/Triticum_aestivum_adapted_2023.xml"

# Notebook reference (day 7.0 -> 7.083 substep, dt=2/24)
NOTEBOOK_REF = {
    "C_ST_mean":  1.78,
    "C_ST_min":   1.64,
    "C_ST_max":   1.87,
    "Rm":         0.0104,
    "Gr":         0.00725,
    "Exud":       0.0379,
    "AnSum":      0.102,
    "Rm_pct":     18.8,
    "Gr_pct":     13.0,
    "Exud_pct":   68.2,
}

BABST_MET = {
    d: {"T_mean_C": 20.75, "T_min_C": 19.0, "T_max_C": 22.0,
        "PAR_MJ_m2_d": 30.0 * 0.219, "VPD_kPa": 1.0,
        "RH_pct": 60.0, "Wind_m_s": 0.5}
    for d in range(1, 60)
}


def _suppress():
    o1 = os.dup(1); o2 = os.dup(2); dn = os.open(os.devnull, os.O_WRONLY)
    os.dup2(dn, 1); os.dup2(dn, 2)
    return o1, o2, dn


def _restore(o1, o2, dn):
    os.dup2(o1, 1); os.dup2(o2, 2)
    os.close(dn); os.close(o1); os.close(o2)


def _legacy_kr_kx_psi_air_per_step(hm, TairC, RH, *, kr_length=0.8):
    """PiafMunch follow-up #4 (2026-05-08): per-step xylem-regime refresh.

    Mirrors `modelparameter/functional/plant_hydraulics/wheat_Giraud2023adapted.py`
    ::setKrKx_xylem applied per simulation step (which is what the FSPM2023
    notebook does in cell 13). Computes water viscosity μ(TairC) and
    refreshes kr/kx on `hm.params` (PlantHydraulicParameters) plus
    `params.psi_air` from RH.

    Why per-step matters: kx ~ 1/μ, and μ varies ~1.4× across the diurnal
    range. Our default helper `tutorial_hydraulic_params_for_weather` is
    called once (frozen at simInit weather). Notebook recomputes kx every
    substep so xylem conductance tracks TairC.

    Why use the legacy kr_length=0.8 here: the notebook does, and we are
    probing whether per-step *refresh* of the same regime keeps the system
    in a viable hydraulic envelope (i.e. whether the failure of follow-up
    #2's once-only kr_length=0.8 was specifically a once-only-ness
    artefact, not a kr_length-itself artefact).
    """
    hPa2cm = 1.0197
    d_water = (
        999.83952
        + TairC
        * (
            16.952577
            + TairC
            * (
                -0.0079905127
                + TairC
                * (-0.000046241757 + TairC * (0.00000010584601 + TairC * -0.00000000028103006))
            )
        )
    ) / (1 + 0.016887236 * TairC)
    si_phi = (30 - TairC) / (91 + TairC)
    mu = pow(10, -0.114 + (si_phi * 1.1))
    mu = mu / (24 * 60 * 60) / 100 / 1000
    mu = mu * hPa2cm  # cmh2o · d

    v_leaf = 32
    v_stem = 52
    v_root = 1
    kz_l = v_leaf * ((0.0015**4) * 2 + (0.0005**4) * 2) * np.pi / (mu * 8)
    kz_s = v_stem * ((0.0017**4) * 3 + (0.0008**4) * 1) * np.pi / (mu * 8)
    kz_r0 = v_root * (0.0015**4) * 4 * np.pi / (mu * 8)
    kz_r1 = v_root * ((0.00041**4) * 4 + (0.00087**4) * 1) * np.pi / (mu * 8)
    kz_r2 = kz_r1
    kz_r3 = v_root * (0.00068**4) * np.pi / (mu * 8)

    kr_l = 3.83e-4 * hPa2cm
    kr_s = 0.0
    kr_r0 = 6.37e-5 * hPa2cm
    kr_r1 = 7.9e-5 * hPa2cm
    kr_r2 = 7.9e-5 * hPa2cm
    kr_r3 = 6.8e-5 * hPa2cm

    root, stem, leaf = 2, 3, 4
    params = hm.params
    # stem + leaf first (whole-segment kr; binds kr_perType callback)
    for st in [0, 1]:
        params.set_kr_const(kr_s, subType=st, organType=stem)
        params.set_kx_const(kz_s, subType=st, organType=stem)
    for st in range(0, 12):
        params.set_kr_const(kr_l, subType=st, organType=leaf)
        params.set_kx_const(kz_l, subType=st, organType=leaf)
    # root LAST — final setKrConst call binds kr_RootExchangeZonePerType
    # (which still dispatches stem + leaf via kr_values directly, see
    # PlantHydraulicParameters.cpp:136-141).
    for st, kr, kx in [
        (0, kr_r0, kz_r0),
        (1, kr_r1, kz_r1),
        (2, kr_r2, kz_r2),
        (3, kr_r0, kz_r0),
        (4, kr_r3, kz_r3),
    ]:
        params.setKrConst(kr, subType=st, organType=root, kr_length=kr_length)
        params.set_kx_const(kx, subType=st, organType=root)

    Rgaz = 8.314
    rho_h2o = d_water / 1000.0
    Mh2o = 18.05
    MPa2hPa = 10000.0
    hPa2cm_psi = 1.0 / 0.9806806
    params.psi_air = (
        np.log(RH) * Rgaz * rho_h2o * (TairC + 273.15) / Mh2o * MPa2hPa * hPa2cm_psi
    )


def _audit_psixyl_summary(hm, plant):
    """Print psiXyl distribution by organ class. Fpsi gates Q_Grmax to 0
    when psiXyl < psi_p_symplasm threshold (default ≈ −2039 cm); the audit
    localises whether the model is in a viable hydraulic envelope."""
    psixyl = np.array(hm.psiXyl, dtype=float)
    if psixyl.size == 0:
        print("  audit-psixyl: psiXyl is empty (loop produced no nodes?)")
        return
    seg2cell = np.array(plant.seg2cell_, dtype=int) if hasattr(plant, "seg2cell_") else None
    seg_org_types = np.array(plant.organTypes, dtype=int) if hasattr(plant, "organTypes") else None
    print()
    print("=" * 100)
    print(f"psiXyl audit ({psixyl.size} nodes)")
    print("=" * 100)
    print(f"  global   min/mean/max [cm]: {psixyl.min():.1f} / {psixyl.mean():.1f} / {psixyl.max():.1f}")
    psi_thr_raw = getattr(hm, "psi_p_symplasm", None)
    if isinstance(psi_thr_raw, (list, np.ndarray)) and len(psi_thr_raw) > 0:
        psi_thr = float(np.asarray(psi_thr_raw).ravel()[0])
    else:
        # Fallback to abs(psiMin); runPM.cpp uses psi_p_symplasm = -psiMin
        psi_thr = -float(getattr(hm, "psiMin", 2039.4))
    n_below = int((psixyl < psi_thr).sum())
    print(f"  psi_p_symplasm threshold: {psi_thr:.1f} cm")
    print(f"  nodes below threshold (Fpsi → 0): {n_below}/{psixyl.size}")
    if seg_org_types is not None and seg_org_types.size + 1 == psixyl.size:
        # psiXyl is per-node (n_segs+1); seg_org_types is per-segment.
        # For per-class summary, propagate seg organType to its child node.
        node_ot = np.zeros(psixyl.size, dtype=int)
        node_ot[1:] = seg_org_types
        for ot, name in [(2, "root"), (3, "stem"), (4, "leaf")]:
            mask = node_ot == ot
            if mask.sum() == 0:
                continue
            psi = psixyl[mask]
            below = int((psi < psi_thr).sum())
            print(f"  {name:5s} (n={mask.sum():>5d}): "
                  f"min/mean/max = {psi.min():.1f} / {psi.mean():.1f} / {psi.max():.1f}  "
                  f"({below}/{mask.sum()} below thr)")
    print()


def build_wheat_tutorial():
    import plantbox as pb
    from climate.dummyWeather import weather

    sim_init = 7.0
    sim_max  = 8.0
    dt       = 2.0 / 24.0
    depth    = 60.0
    weather_init = weather(sim_init)

    plant = pb.MappedPlant(seednum=2)
    plant.readParameters(str(WHEAT_XML))
    plant.setGeometry(pb.SDF_PlantBox(np.inf, np.inf, depth))
    plant.initialize(False)
    plant.simulate(sim_init, False)
    picker = lambda x, y, z: max(int(np.floor(-z)), -1)
    plant.setSoilGrid(picker)
    return plant, dict(sim_init=sim_init, sim_max=sim_max, dt=dt,
                       depth=depth, weather_init=weather_init)


def build_maize(age_days):
    Tair_C = 20.75
    plant = grow_plant(
        xml_path=str(DEFAULT_XML),
        simulation_time=age_days,
        min_stem_nodes=10,
        min_leaf_nodes=4,
        enable_photosynthesis=True,
        seed=42,
        daily_met=BABST_MET,
        T_air_default=Tair_C,
    )
    # PM compat (D1+D2+D3, 2026-05-08): grow_plant leaves stems on
    # MultiPhaseStemGrowth, leaves on MultiPhaseLeafGrowth, roots on the
    # base GrowthFunction wrapper. None of these consume f_gf->CW_Gr in
    # getLength; PM fills the map at substep 1 and substep 2 trips
    # PhloemFlux::assertUsedCReserves. Wrap with CWLimitedGrowth (the
    # production diurnal.py path at diurnal.py:1627) so getLength
    # consumes CW_Gr (-> -1.0) and the carbon supply is actually applied
    # to plant growth. wrap_roots=False keeps the
    # [[project_root_path_preservation]] contract: bare CWLimitedGrowth
    # on roots is enough for consumption.
    from dart.coupling.growth.carbon_growth import enable_cw_limited_growth
    enable_cw_limited_growth(plant)
    return plant, dict(sim_init=float(age_days),
                       sim_max=float(age_days) + 1.0,
                       dt=1.0 / 24.0, Tair_C=Tair_C)


def configure_wheat_tutorial(hm, weather_init):
    """Mirror the notebook's r.* configuration (cell 11)."""
    from plant_photosynthesis.wheat_FcVB_Giraud2023adapted import (
        setPhotosynthesisParameters,
    )
    from plant_sucrose.wheat_phloem_Giraud2023adapted import setKrKx_phloem

    setPhotosynthesisParameters(hm, weather_init)
    setKrKx_phloem(hm)
    hm.setKrm2([[2e-5]])
    hm.setKrm1([[10e-2]])
    hm.setRhoSucrose([[0.51], [0.65], [0.56]])
    hm.setRmax_st([[14.4, 9.0, 6.0, 14.4], [5.0, 5.0], [15.0]])
    hm.KMfu = 0.11
    hm.beta_loading = 0.6
    hm.Vmaxloading = 0.05
    hm.Mloading = 0.2
    hm.Gr_Y = 0.8
    hm.CSTimin = 0.4
    hm.Csoil = 1e-4
    hm.update_viscosity = True
    hm.atol = 1e-12
    hm.rtol = 1e-8
    return hm


def configure_maize(hm, **overrides):
    hm.read_phloem_parameters(filename=get_phloem_json())
    hm.atol = 1e-6
    hm.rtol = 1e-4
    for k, v in overrides.items():
        setattr(hm, k, v)
    return hm


def run_loop(plant, sim_init, sim_max, dt, hm,
             solve_photosynthesis_fn, Tair_C_at,
             label="run", verbose=False):
    """Mirror the notebook loop. Returns per-substep results."""
    Q_Rmbu   = np.zeros(0)
    Q_Grbu   = np.zeros(0)
    Q_Exudbu = np.zeros(0)
    AnSum = 0.0
    rows = []

    sim = float(sim_init)
    pm_filename = str(REPO_ROOT / "dart/coupling/scripts/_pm_nb_loop.txt")

    while sim <= sim_max + 1e-9:
        nt = len(plant.getNodes())
        Tair_C = float(Tair_C_at(sim))
        Tair_K = Tair_C + 273.15

        # 1) Photosynthesis update.
        solve_photosynthesis_fn(hm, sim, Tair_C)

        # cumulative An via Ag4Phloem * dt (notebook line: AnSum += np.sum(r.Ag4Phloem)*dt)
        Ag = np.array(hm.Ag4Phloem)
        AnSum += float(np.sum(Ag)) * dt

        # 2) PiafMunch substep.
        fdpair = _suppress()
        try:
            ret = hm.startPM(sim, sim + dt, 1, Tair_K, True, pm_filename)
        finally:
            _restore(*fdpair)
        if ret != 1:
            print(f"  startPM returned {ret} at t={sim:.4f}")
            return rows

        # 3) Read state (per notebook cell 13).
        Q_ST   = np.array(hm.Q_out[0:nt])
        Q_meso = np.array(hm.Q_out[nt:(nt*2)])
        Q_Rm   = np.array(hm.Q_out[(nt*2):(nt*3)])
        Q_Exud = np.array(hm.Q_out[(nt*3):(nt*4)])
        Q_Gr   = np.array(hm.Q_out[(nt*4):(nt*5)])
        C_ST   = np.array(hm.C_ST)

        # Per-step deltas
        Q_ST_i   = Q_ST  # not differenced; absolute since AnSum is also absolute
        if Q_Rmbu.size != Q_Rm.size:
            Q_Rmbu   = np.zeros_like(Q_Rm)
            Q_Grbu   = np.zeros_like(Q_Gr)
            Q_Exudbu = np.zeros_like(Q_Exud)
        d_Rm   = float(np.sum(Q_Rm   - Q_Rmbu))
        d_Gr   = float(np.sum(Q_Gr   - Q_Grbu))
        d_Exud = float(np.sum(Q_Exud - Q_Exudbu))
        d_out  = d_Rm + d_Gr + d_Exud

        rows.append(dict(
            sim=sim, dt=dt, AnSum=AnSum,
            sum_Q_ST=float(np.sum(Q_ST)),
            sum_Q_meso=float(np.sum(Q_meso)),
            cum_Q_Rm=float(np.sum(Q_Rm)),
            cum_Q_Gr=float(np.sum(Q_Gr)),
            cum_Q_Exud=float(np.sum(Q_Exud)),
            d_Rm=d_Rm, d_Gr=d_Gr, d_Exud=d_Exud,
            Rm_pct=100*d_Rm / d_out if d_out > 0 else 0,
            Gr_pct=100*d_Gr / d_out if d_out > 0 else 0,
            Exud_pct=100*d_Exud / d_out if d_out > 0 else 0,
            C_ST_mean=float(np.mean(C_ST)),
            C_ST_min=float(np.min(C_ST)),
            C_ST_max=float(np.max(C_ST)),
        ))

        if verbose:
            r = rows[-1]
            print(f"  t={sim:.4f}  An_cum={AnSum:.4e}  "
                  f"Q_Rm={r['cum_Q_Rm']:.4e}  Q_Gr={r['cum_Q_Gr']:.4e}  "
                  f"Q_Exud={r['cum_Q_Exud']:.4e}  C_ST mean/max={r['C_ST_mean']:.3f}/{r['C_ST_max']:.3f}  "
                  f"split Rm/Gr/Exud {r['Rm_pct']:.1f}/{r['Gr_pct']:.1f}/{r['Exud_pct']:.1f}")

        Q_Rmbu   = Q_Rm.copy()
        Q_Grbu   = Q_Gr.copy()
        Q_Exudbu = Q_Exud.copy()

        # 4) Plant grows -- this is the step that consumes CW_Gr and lets useCWGr=True work.
        fdpair = _suppress()
        try:
            plant.simulate(dt, False)
        finally:
            _restore(*fdpair)

        sim += dt

    p = Path(pm_filename)
    if p.exists():
        p.unlink()
    return rows


def case_wheat_tutorial(verbose, *, legacy_perstep=None, audit_psixyl=False):
    print("=" * 100)
    print("Wheat day-7.3 notebook reproduction (binary check)")
    print("=" * 100)
    plant, cfg = build_wheat_tutorial()
    weather_init = cfg["weather_init"]

    from functional.phloem_flux import PhloemFluxPython
    sys.path.insert(0, str(REPO_ROOT / "dart/coupling/scripts"))
    from pm_vs_s5_wheat_tutorial import tutorial_hydraulic_params_for_weather

    p_mean = weather_init["p_mean"]; depth = cfg["depth"]
    p_top = p_mean - depth/2

    # PiafMunch follow-up #2 (2026-05-08): default `notebook_aligned=False`
    # — empirical A/B/C/D probe falsified the plan's hypothesis that
    # aligning to legacy setKrKx_xylem closes the wheat-notebook Q_Gr gap.
    # kr_length=0.8 dropped psiXyl to −13274 cm and Q_Gr to 0 (worse, not
    # better). Pre-fix Q_Gr=7.56e-4 stays the wheat-tutorial baseline.
    hyd = tutorial_hydraulic_params_for_weather(weather_init, plant=plant,
                                                notebook_aligned=False)
    hm = PhloemFluxPython(plant, hyd,
                          psiXylInit=p_top,
                          ciInit=weather_init["cs"] * 0.5)
    configure_wheat_tutorial(hm, weather_init)
    # Notebook does NOT set useCWGr -> default True per runPM.h
    print(f"  useCWGr (default): {bool(hm.useCWGr)}")
    print(f"  legacy-perstep refresh of kr/kx/psi_air: {legacy_perstep}")
    if legacy_perstep == "no_krlen":
        print(f"    (kr_length=-1 whole-segment; isolates viscosity-only effect)")
    print(f"  Loop: simInit={cfg['sim_init']}, simMax={cfg['sim_max']}, dt={cfg['dt']:.4f}")
    print()

    from climate.dummyWeather import weather
    # tutorial_hydraulic_params_for_weather uses the new
    # PlantHydraulicParameters API (setKr/setKx are no longer on hm
    # in the current build — the wheat helper relies on the old API).
    from pm_vs_s5_wheat_tutorial import tutorial_hydraulic_params_for_weather

    p_bot = p_mean + depth/2
    sx = np.linspace(p_top, p_bot, int(depth))

    def solve_photo(hm_, sim_, _Tair_C):
        wx = weather(sim_)
        # PiafMunch follow-up #4 (2026-05-08): per-step xylem refresh
        # (mirroring the FSPM2023 notebook's setKrKx_xylem in cell 13).
        # kr/kx scale with 1/μ(TairC); μ varies ~1.4× across diurnal range.
        if legacy_perstep == "with_krlen":
            _legacy_kr_kx_psi_air_per_step(hm_, float(wx["TairC"]),
                                           float(wx["RH"]),
                                           kr_length=0.8)
        elif legacy_perstep == "no_krlen":
            _legacy_kr_kx_psi_air_per_step(hm_, float(wx["TairC"]),
                                           float(wx["RH"]),
                                           kr_length=-1.0)
        hm_.Qlight = [float(wx["Qlight"])]
        hm_.cs = [float(wx["cs"])]
        TleafK = [wx["TairC"] + 273.15]
        fdpair = _suppress()
        try:
            hm_.solve_photosynthesis(
                sim_time=sim_, sxx=sx,
                ea=wx["ea"], es=wx["es"],
                TleafK=TleafK,
                cells=True, doLog=False, verbose=False,
            )
        finally:
            _restore(*fdpair)

    Tair_C_at = lambda sim_: weather(sim_)["TairC"]

    t0 = _time.time()
    rows = run_loop(plant, cfg["sim_init"], cfg["sim_max"], cfg["dt"],
                    hm, solve_photo, Tair_C_at, label="wheat", verbose=verbose)
    wall = _time.time() - t0
    print(f"\nLoop wall: {wall:.1f}s, {len(rows)} substeps")

    if not rows:
        print("Loop produced no rows -- likely solver failure.")
        return None

    if audit_psixyl:
        _audit_psixyl_summary(hm, plant)

    first = rows[0]   # day 7.0 -> 7.083 substep
    print()
    print("=" * 100)
    print("FIRST-SUBSTEP COMPARISON TO NOTEBOOK REFERENCE")
    print("=" * 100)
    print(f"{'metric':<22} {'model':>14} {'notebook':>14} {'ratio':>10} {'verdict':>8}")
    print("-" * 70)
    pairs = [
        ("AnSum",      "AnSum",       NOTEBOOK_REF["AnSum"]),
        ("C_ST_mean",  "C_ST_mean",   NOTEBOOK_REF["C_ST_mean"]),
        ("C_ST_min",   "C_ST_min",    NOTEBOOK_REF["C_ST_min"]),
        ("C_ST_max",   "C_ST_max",    NOTEBOOK_REF["C_ST_max"]),
        ("cum Rm",     "cum_Q_Rm",    NOTEBOOK_REF["Rm"]),
        ("cum Gr",     "cum_Q_Gr",    NOTEBOOK_REF["Gr"]),
        ("cum Exud",   "cum_Q_Exud",  NOTEBOOK_REF["Exud"]),
        ("split Rm %", "Rm_pct",      NOTEBOOK_REF["Rm_pct"]),
        ("split Gr %", "Gr_pct",      NOTEBOOK_REF["Gr_pct"]),
        ("split Exud%","Exud_pct",    NOTEBOOK_REF["Exud_pct"]),
    ]
    n_pass = 0
    n_total = 0
    for label, key, ref in pairs:
        val = first[key]
        if ref == 0:
            ratio = float('inf') if val != 0 else 1.0
        else:
            ratio = val / ref
        within = (0.5 <= ratio <= 2.0) if ref != 0 else (val == 0)
        verdict = "PASS" if within else "FAIL"
        n_total += 1
        if within: n_pass += 1
        print(f"{label:<22} {val:>14.4g} {ref:>14.4g} {ratio:>10.3f} {verdict:>8}")

    print("-" * 70)
    print(f"  {n_pass}/{n_total} metrics within 2x of notebook reference.")
    print()
    if n_pass >= 7:
        print(">>> BINARY CHECK PASS: PM with useCWGr=True+plant.simulate matches notebook.")
        print("    Multi-session 'PiafMunch broken' diagnosis was a harness artifact.")
    elif n_pass >= 4:
        print(">>> BINARY CHECK PARTIAL: some metrics match, some don't. Investigate per-row.")
    else:
        print(">>> BINARY CHECK FAIL: PM diverges from notebook even in correct mode.")
        print("    Real model issue persists -- harness fix alone insufficient.")
    return rows


def case_maize(age_days, verbose):
    print("=" * 100)
    print(f"Maize day-{age_days} with useCWGr=True + plant.simulate loop")
    print("=" * 100)
    plant, cfg = build_maize(age_days)
    Tair_C = cfg["Tair_C"]

    from functional.phloem_flux import PhloemFluxPython
    from plantbox.functional.PlantHydraulicParameters import PlantHydraulicParameters
    params_h = PlantHydraulicParameters()
    params_h.read_parameters(get_hydraulics_json())

    hm = PhloemFluxPython(plant, params_h, psiXylInit=-500, ciInit=350e-6)
    hm.read_photosynthesis_parameters(filename=get_photosynthesis_json())
    configure_maize(hm, Vmaxloading=0.20, beta_loading=2.0, solver=32)
    print(f"  useCWGr (default): {bool(hm.useCWGr)}  Vmax=0.20  beta=2.0")
    print(f"  Loop: from {cfg['sim_init']:.1f} to {cfg['sim_max']:.1f}, dt={cfg['dt']*24:.1f}h")

    p_s = np.linspace(-500, -700, 200)

    def solve_photo(hm_, sim_, T):
        es = hm_.get_es(T); ea = es * 0.6
        par = 600.0 * 1e-6 * 86400 * 1e-4
        fdpair = _suppress()
        try:
            hm_.solve(sim_time=sim_, rsx=p_s, cells=True, ea=ea, es=es,
                      PAR=par, TairC=T, verbose=0)
        finally:
            _restore(*fdpair)

    Tair_C_at = lambda sim_: Tair_C
    t0 = _time.time()
    rows = run_loop(plant, cfg["sim_init"], cfg["sim_max"], cfg["dt"],
                    hm, solve_photo, Tair_C_at, label=f"maize_d{age_days}", verbose=verbose)
    wall = _time.time() - t0
    print(f"\nLoop wall: {wall:.1f}s, {len(rows)} substeps")

    if not rows:
        return None

    last = rows[-1]
    total_sinks = last["cum_Q_Rm"] + last["cum_Q_Gr"] + last["cum_Q_Exud"]
    load_eff = total_sinks / last["AnSum"] if last["AnSum"] > 0 else 0
    print()
    print(f"24h cumulative (mmol Suc):")
    print(f"  AnSum   : {last['AnSum']:.3f}")
    print(f"  Rm      : {last['cum_Q_Rm']:.3f}  ({100*last['cum_Q_Rm']/last['AnSum']:.1f}% of An)" if last['AnSum']>0 else "  Rm     : 0")
    print(f"  Gr      : {last['cum_Q_Gr']:.3f}  ({100*last['cum_Q_Gr']/last['AnSum']:.1f}%)" if last['AnSum']>0 else "  Gr     : 0")
    print(f"  Exud    : {last['cum_Q_Exud']:.3f}  ({100*last['cum_Q_Exud']/last['AnSum']:.1f}%)" if last['AnSum']>0 else "  Exud   : 0")
    print(f"  Σsinks/An (load_eff proxy) : {load_eff:.3f}")
    print(f"  C_ST mean/min/max          : {last['C_ST_mean']:.3f} / {last['C_ST_min']:.3f} / {last['C_ST_max']:.3f}")
    print()
    if last["cum_Q_Gr"] > 0.01 * last["AnSum"]:
        print(">>> Rg > 1% of An -- carbon-limited growth path is ACTIVE in this run.")
    else:
        print(">>> Rg still negligible. Issue may extend beyond useCWGr toggle.")
    return rows


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--case", choices=("wheat_tutorial", "v3_maize", "day55_maize", "all"),
                   default="wheat_tutorial")
    p.add_argument("-v", "--verbose", action="store_true")
    p.add_argument("--legacy-perstep", action="store_true",
                   help="(wheat_tutorial only) Refresh kr/kx/psi_air on hm.params "
                        "per substep with kr_length=0.8 (mirrors FSPM2023 notebook).")
    p.add_argument("--legacy-perstep-no-krlen", action="store_true",
                   help="(wheat_tutorial only) Per-step refresh but kr_length=-1 "
                        "(whole-segment kr). Isolates viscosity-only effect from "
                        "the kr exchange-zone effect.")
    p.add_argument("--audit-psixyl", action="store_true",
                   help="(wheat_tutorial only) After the loop, dump psiXyl summary "
                        "(min/mean/max by organ class) to localise water-stress.")
    args = p.parse_args()

    out = {}
    if args.case in ("wheat_tutorial", "all"):
        if args.legacy_perstep and args.legacy_perstep_no_krlen:
            raise SystemExit("--legacy-perstep and --legacy-perstep-no-krlen are mutually exclusive")
        legacy_mode = None
        if args.legacy_perstep:
            legacy_mode = "with_krlen"
        elif args.legacy_perstep_no_krlen:
            legacy_mode = "no_krlen"
        out["wheat_tutorial"] = case_wheat_tutorial(
            args.verbose,
            legacy_perstep=legacy_mode,
            audit_psixyl=args.audit_psixyl)
    if args.case in ("v3_maize", "all"):
        print()
        out["v3_maize"] = case_maize(21, args.verbose)
    if args.case in ("day55_maize", "all"):
        print()
        out["day55_maize"] = case_maize(55, args.verbose)

    out_json = REPO_ROOT / f"dart/coupling/scripts/_pm_notebook_loop_{args.case}.json"
    with open(out_json, 'w') as f:
        json.dump(out, f, indent=2, default=str)
    print(f"\nJSON dump: {out_json}")


if __name__ == "__main__":
    main()
